name: Friday Countdown Bot

on:
  schedule:
    - cron: "*/6 * * * *"  # Every 6 minutes
  workflow_dispatch:        # Allow manual run from GitHub UI

jobs:
  tweet:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET: ${{ secrets.API_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy python-dotenv

      - name: Run bot
        run: python main.py
